=== reheda/Tpad/src/main/resources/dbSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://hak.pp.ua/dbSchema" xmlns:tns="http://hak.pp.ua/dbSchema"
	elementFormDefault="qualified">


	<xsd:element name="attributes">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="attribute" type="tns:AttributeFeature"
					minOccurs="0" maxOccurs="unbounded" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="AttributeFeature">
		<xsd:sequence>
			<xsd:element name="id" type="xsd:positiveInteger" />
			<xsd:element name="type" type="tns:TypeFeature" />
			<xsd:element name="name" type="xsd:string" />
			<xsd:element name="deactivated" type="tns:DeactivatedFeature" />
			<xsd:element name="group-id" type="xsd:positiveInteger" />
			<xsd:element name="group-name" type="xsd:string" />
			<xsd:element name="last-update" type="xsd:string" />
		</xsd:sequence>
	</xsd:complexType>


	<xsd:simpleType name="TypeFeature">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="Simple" />
			<xsd:enumeration value="Simple numeric" />
			<xsd:enumeration value="Multi-valued" />
			<xsd:enumeration value="Multi-valued numeric" />
			<xsd:enumeration value="Repeating" />
			<xsd:enumeration value="Repeating numeric" />
		</xsd:restriction>
	</xsd:simpleType>

	<xsd:simpleType name="DeactivatedFeature">
		<xsd:restriction base="xsd:string">
			<xsd:enumeration value="true" />
			<xsd:enumeration value="false" />
		</xsd:restriction>
	</xsd:simpleType>
</xsd:schema>

=== reheda/Tpad/helpers/db.xml
<?xml version="1.0" encoding="UTF-8"?>

<attributes xmlns="http://hak.pp.ua/dbSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://hak.pp.ua/dbSchema dbSchema.xsd">
	<attribute> <id>10652</id> <type>Simple</type>  <name>Design</name> <deactivated>false</deactivated> <group-id>464</group-id> <group-name>General</group-name> <last-update>11/03/2017</last-update> </attribute>
	<attribute> <id>10676</id> <type>Simple</type>  <name>Power Source</name> <deactivated>false</deactivated> <group-id>349</group-id> <group-name>Power</group-name> <last-update>11/03/2017</last-update> </attribute>
	<attribute> <id>10691</id> <type>Simple</type>  <name>Built-in LED Energy Efficiency Class</name> <deactivated>false</deactivated> <group-id>603</group-id> <group-name>Light Bulb</group-name> <last-update>11/03/2017</last-update> </attribute>
	<attribute> <id>10694</id> <type>Repeating</type>  <name>Type</name> <deactivated>false</deactivated> <group-id>786</group-id> <group-name>Car Video Recording System Details</group-name> <last-update>11/03/2017</last-update> </attribute>
	<attribute> <id>10695</id> <type>Repeating</type>  <name>Qty</name> <deactivated>false</deactivated> <group-id>786</group-id> <group-name>Car Video Recording System Details</group-name> <last-update>11/03/2017</last-update> </attribute>
	<attribute> <id>10696</id> <type>Repeating numeric</type>  <name>Sensor Resolution</name> <deactivated>false</deactivated> <group-id>786</group-id> <group-name>Car Video Recording System Details</group-name> <last-update>11/03/2017</last-update> </attribute>
	<attribute> <id>5959</id> <type>Multi-valued</type>  <name>Recycled</name> <deactivated>true</deactivated> <group-id>130</group-id> <group-name>Additional Attributes</group-name> <last-update>00/01/1900</last-update> </attribute>
</attributes>
