=== reheda/Tpad/src/main/resources/settingsSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://hak.pp.ua/settingsSchema" xmlns:tns="http://hak.pp.ua/settingsSchema"
	elementFormDefault="qualified">

	<xsd:element name="settings">
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element name="font" type="tns:FontFeature" />
				<xsd:element name="foreground" type="tns:ColorFeature" />
				<xsd:element name="background" type="tns:ColorFeature" />
				<xsd:element name="keyword" type="tns:ColorFeature" />
				<xsd:element name="comment" type="tns:ColorFeature" />
				<xsd:element name="string" type="tns:ColorFeature" />
				<xsd:element name="wordwrap" type="tns:StatusFeature" />
				<xsd:element name="statusbar" type="tns:StatusFeature" />
				<xsd:element name="parserpanel" type="tns:StatusFeature" />
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>

	<xsd:complexType name="FontFeature">
		<xsd:sequence>
			<xsd:element name="name" type="xsd:string" />
			<xsd:element name="style" type="xsd:integer" />
			<xsd:element name="size" type="xsd:integer" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="ColorFeature">
		<xsd:sequence>
			<xsd:element name="color" type="xsd:integer" />
		</xsd:sequence>
	</xsd:complexType>

	<xsd:complexType name="StatusFeature">
		<xsd:sequence>
			<xsd:element name="enable" type="xsd:boolean" />
		</xsd:sequence>
	</xsd:complexType>


</xsd:schema>

=== reheda/Tpad/settings.xml
<?xml version="1.0" encoding="UTF-8"?><settings xmlns="http://hak.pp.ua/settingsSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://hak.pp.ua/settingsSchema settingsSchema.xsd"><font><name>Consolas</name><style>0</style><size>14</size></font><foreground><color>-16777216</color></foreground><background><color>-1</color></background><wordwrap><enable>true</enable></wordwrap><statusbar><enable>true</enable></statusbar><parserpanel><enable>true</enable></parserpanel></settings>
